apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: CILIUMLBCIDR
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 