apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-components
  namespace: argocd  # must stay here for Argo CD
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  generators:
  - git:
      repoURL: https://github.com/Aschonn/argocd-homelab.git
      revision: HEAD
      directories:
        - path: infra/metrics-server/kustomize
  template:
    metadata:
      name: metrics-server
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/Aschonn/argocd-homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
