apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-components
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  generators:
  - git:
      repoURL: https://github.com/Aschonn/argocd-homelab.git
      revision: HEAD
      directories:
      - path: infra/metrics-server/kustomize
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        type: infrastructure
    spec:
      project: default
      source:
        plugin:
          name: kustomize-build-with-helm
        repoURL: https://github.com/Aschonn/argocd-homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
        - RespectIgnoreDifferences=true
        - ApplyOutOfSyncOnly=true
        - Replace=false
        - IgnoreMissingTemplate=true