apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure-components
  namespace: argocd  # must stay here for Argo CD
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  generators:
    - git:
        repoURL: https://github.com/Aschonn/argocd-homelab.git
        revision: HEAD
        directories:
          - path: infra/monitoring/*
          - path: infra/controllers/*
  template:
    metadata:
      name: '{{path.basename}}'
      labels:
        type: infrastructure
      annotations:
        argocd.argoproj.io/kustomize-build-options: "--enable-helm"
    spec:
      project: default
      source:
        repoURL: https://github.com/Aschonn/argocd-homelab.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
