apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
spec:
  blocks:
    - cidr: "192.168.0.224/28"  # Use "blocks" instead of "cidrs" Usable IPs: 192.168.0.225 – 192.168.0.238
  allowFirstLastIPs: "No"  # Required in Cilium 1.16+ if reserving first/last IPs 
